### PR TITLE
Handle lack of shared if a bookmark is public

### PR DESCRIPTION
**Pull request by davep**
Looking at the XML data coming back from pinboard.in, it would appear that if a bookmark is private, then the `shared` value exists in the data and is set to "no"; if it's set in the interface on the website to public (private isn't ticked), then the `shared` value isn't in the data at all.

So checking if shared is "yes" means every bookmark will always appear to be private as seen via this library.

This tweak to the checking of `shared` means that the data will end up correct in the `Bookmark` object. At the moment *every* bookmark appears to be private no matter how it is set in `pinboard.in`.

### CODE REVIEW

**Review by bachya — APPROVED** [review]
Great catch!

**Comment by davep** [comment]
(skipping over to a different PR from the possible release question) -- I'm just retesting all of this with the `dev` branch as an editable install for my project and everything still seems to be coming down the line as a private bookmark, even when it's public. I need to step away from the keyboard for a couple or so hours so can't dive into it right now, but I'm wondering if I didn't manage to fix that with this after all.

**Comment by bachya** [comment]
Roger, I'll hold cutting a release.

**Comment by davep** [comment]
Actually, no, we're all good, I'm an idiot. I cache the bookmarks as much as possible, and was doing a final check with a copy of the data last cached with the `shared` issue in place, when what I should have done is nuke the cache and start the check again. 🤦🏻‍♀️

So, yeah, feel free to release when you're up for it. :-D

**Pull request merged**
