### PR TITLE
Migrate from Pinboard's XML API to its JSON API

### LINKED ISSUE #300: Line breaks are lost from the description when retrieving a bookmark
**Describe the bug**
If a bookmark is created such that it has line breaks in the description, when the bookmark is retrieved by the library, the line breaks are lost.

**To Reproduce**
Run this code, supplying a valid API token:

```python
from asyncio import run
from aiopinboard import API

TOKEN = "<token here>"

URL = "https://www.example.com/multiple-lines"

async def show_problem():
    await API(TOKEN).bookmark.async_add_bookmark(
        url=URL,
        title=f"Test multiple lines",
        description="\n".join(f"Line {n}" for n in range(10)),
        shared=False,
        toread=True,
        replace=True,
    )
    print((await API(TOKEN).bookmark.async_get_bookmark_by_url(URL)).description)

if __name__ == "__main__":
    run(show_problem())
```

**Expected behavior**
It would be expected that the content of the description would match that found on Pinboard itself. With the above code, the bookmark that appears on Pinboard has the line breaks:

Screenshot 2023-12-13 at 15 12 45

but the above script prints this:

```
Line 0 Line 1 Line 2 Line 3 Line 4 Line 5 Line 6 Line 7 Line 8 Line 9
```

### PR DESCRIPTION
**Pull request by bachya**
**Describe what the PR does:**

SSIA. This should be a drop-in replacement and shouldn't cause any breaking change for this library.

**Does this fix a specific issue?**

Fixes https://github.com/bachya/aiopinboard/issues/300

**Checklist:**

- [x] Confirm that one or more new tests are written for the new functionality.
- [x] Run tests and ensure everything passes (with 100% test coverage).
- [ ] Update `README.md` with any new documentation.

### CODE REVIEW

**Comment by davep** [comment]
Just gave this a spin, plugging it into [my app at v0.0.7](https://github.com/davep/tinboard/releases/tag/v0.0.7), and I get this `RequestError`:

`Attempt to decode JSON with unexpected mimetype: text/json; charset=utf-8', url=URL('https://api.pinboard.in/v1/posts/all?start=0&auth_token=xxx&format=json')`


(where the `auth_token` is removed, of course)

**Comment by bachya** [comment]
Good catch, @davep. Fixed.

**Comment by bachya** [comment]
@davep Happy New Year! Have you had a chance to confirm whether my latest commit fixes the issue you were seeing?

**Comment by davep** [comment]
Hey! Sorry about that, I think I missed notifications of more work on the PR. When I get a moment I'll give it another run through. :-)

**Comment by davep** [comment]
Tested with `tinboard` and it's looking good; bookmarks pull down fine, changes upload fine too.

**Comment by bachya** [comment]
@davep FYI, just cut [2024.01.0](https://github.com/bachya/aiopinboard/releases/tag/2024.01.0), which includes this update.

**Comment by davep** [comment]
Awesome. Thanks.

**Pull request merged**
